version: "3.3"

services:
  bot:
    env_file:
      - .env
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    environment:
      - DB_URL=postgresql://admin:admin@db:5432/bot_db
    depends_on: [db]
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "bot_db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: "/var/lib/postgresql/data"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d bot_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    expose:
      - 5432
    ports:
      - "5432:5432"
    restart: unless-stopped